// Create an array of objects with dynamic data
const data1 = [
  { name: "John", age: 28, gender: "Male", city: "New York" },
  { name: "Sarah", age: 32, gender: "Female", city: "Los Angeles" },
  { name: "Tom", age: 25, gender: "Male", city: "Chicago" },
  { name: "Jane", age: 30, gender: "Female", city: "San Francisco" },
  { name: "Alex", age: 35, gender: "Male", city: "Seattle" },
  { name: "Emily", age: 29, gender: "Female", city: "Denver" },
  { name: "Mike", age: 27, gender: "Male", city: "Austin" },
  { name: "Jenny", age: 31, gender: "Female", city: "Boston" },
  { name: "Chris", age: 26, gender: "Male", city: "Atlanta" },
  { name: "Lily", age: 33, gender: "Female", city: "Miami" },
  { name: "John1", age: 28, gender: "Male", city: "New York" },
  { name: "Sarah", age: 32, gender: "Female", city: "Los Angeles" },
  { name: "Tom", age: 25, gender: "Male", city: "Chicago" },
  { name: "Jane", age: 30, gender: "Female", city: "San Francisco" },
  { name: "Alex", age: 35, gender: "Male", city: "Seattle" },
  { name: "Emily", age: 29, gender: "Female", city: "Denver" },
  { name: "Mike", age: 27, gender: "Male", city: "Austin" },
  { name: "Jenny", age: 31, gender: "Female", city: "Boston" },
  { name: "Chris", age: 26, gender: "Male", city: "Atlanta" },
  { name: "Lily", age: 33, gender: "Female", city: "Miami" },
  { name: "John2", age: 28, gender: "Male", city: "New York" },
  { name: "Sarah", age: 32, gender: "Female", city: "Los Angeles" },
  { name: "Tom", age: 25, gender: "Male", city: "Chicago" },
  { name: "Jane", age: 30, gender: "Female", city: "San Francisco" },
  { name: "Alex", age: 35, gender: "Male", city: "Seattle" },
  { name: "Emily", age: 29, gender: "Female", city: "Denver" },
  { name: "Mike", age: 27, gender: "Male", city: "Austin" },
  { name: "Jenny", age: 31, gender: "Female", city: "Boston" },
  { name: "Chris", age: 26, gender: "Male", city: "Atlanta" },
  { name: "Lily", age: 33, gender: "Female", city: "Miami" },
  { name: "John3", age: 28, gender: "Male", city: "New York" },
  { name: "Sarah", age: 32, gender: "Female", city: "Los Angeles" },
  { name: "Tom", age: 25, gender: "Male", city: "Chicago" },
  { name: "Jane", age: 30, gender: "Female", city: "San Francisco" },
  { name: "Alex", age: 35, gender: "Male", city: "Seattle" },
  { name: "Emily", age: 29, gender: "Female", city: "Denver" },
  { name: "Mike", age: 27, gender: "Male", city: "Austin" },
  { name: "Jenny", age: 31, gender: "Female", city: "Boston" },
  { name: "Chris", age: 26, gender: "Male", city: "Atlanta" },
  { name: "Lily", age: 33, gender: "Female", city: "Miami" },
  { name: "John4", age: 28, gender: "Male", city: "New York" },
  { name: "Sarah", age: 32, gender: "Female", city: "Los Angeles" },
  { name: "Tom", age: 25, gender: "Male", city: "Chicago" },
  { name: "Jane", age: 30, gender: "Female", city: "San Francisco" },
  { name: "Alex", age: 35, gender: "Male", city: "Seattle" },
  { name: "Emily", age: 29, gender: "Female", city: "Denver" },
  { name: "Mike", age: 27, gender: "Male", city: "Austin" },
  { name: "Jenny", age: 31, gender: "Female", city: "Boston" },
  { name: "Chris", age: 26, gender: "Male", city: "Atlanta" },
  { name: "Lily", age: 33, gender: "Female", city: "Miami" },
  { name: "John5", age: 28, gender: "Male", city: "New York" },
  { name: "Sarah", age: 32, gender: "Female", city: "Los Angeles" },
  { name: "Tom", age: 25, gender: "Male", city: "Chicago" },
  { name: "Jane", age: 30, gender: "Female", city: "San Francisco" },
  { name: "Alex", age: 35, gender: "Male", city: "Seattle" },
  { name: "Emily", age: 29, gender: "Female", city: "Denver" },
  { name: "Mike", age: 27, gender: "Male", city: "Austin" },
  { name: "Jenny", age: 31, gender: "Female", city: "Boston" },
  { name: "Chris", age: 26, gender: "Male", city: "Atlanta" },
  { name: "Lily", age: 33, gender: "Female", city: "Miami" },
];
const data = [
  {
    "Ins No.": 1,
    Date: "2023-03-01",
    "Principal Amount": 1000,
    "Interest Amount": 50,
    "Install Amount": 1050,
    "Collection Date": "2023-03-15",
    "Amount Collected": 1050,
    "Outstanding Principal": 0,
    Sign: "+",
  },
  {
    "Ins No.": 2,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 3,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 4,
    Date: "2023-05-01",
    "Principal Amount": 1000,
    "Interest Amount": 40,
    "Install Amount": 1040,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1040,
    Sign: "-",
  },
  {
    "Ins No.": 5,
    Date: "2023-06-01",
    "Principal Amount": 1000,
    "Interest Amount": 35,
    "Install Amount": 1035,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1035,
    Sign: "-",
  },
  {
    "Ins No.": 6,
    Date: "2023-07-01",
    "Principal Amount": 1000,
    "Interest Amount": 30,
    "Install Amount": 1030,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1030,
    Sign: "-",
  },
  {
    "Ins No.": 7,
    Date: "2023-08-01",
    "Principal Amount": 1000,
    "Interest Amount": 25,
    "Install Amount": 1025,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1025,
    Sign: "-",
  },
  {
    "Ins No.": 8,
    Date: "2023-09-01",
    "Principal Amount": 1000,
    "Interest Amount": 20,
    "Install Amount": 1020,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1020,
    Sign: "-",
  },
  {
    "Ins No.": 9,
    Date: "2023-10-01",
    "Principal Amount": 1000,
    "Interest Amount": 15,
    "Install Amount": 1015,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1015,
    Sign: "-",
  },
  {
    "Ins No.": 10,
    Date: "2023-11-01",
    "Principal Amount": 1000,
    "Interest Amount": 10,
    "Install Amount": 1010,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1010,
    Sign: "-",
  },
  {
    "Ins No.": 1,
    Date: "2023-03-01",
    "Principal Amount": 1000,
    "Interest Amount": 50,
    "Install Amount": 1050,
    "Collection Date": "2023-03-15",
    "Amount Collected": 1050,
    "Outstanding Principal": 0,
    Sign: "+",
  },
  {
    "Ins No.": 2,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 3,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 4,
    Date: "2023-05-01",
    "Principal Amount": 1000,
    "Interest Amount": 40,
    "Install Amount": 1040,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1040,
    Sign: "-",
  },
  {
    "Ins No.": 5,
    Date: "2023-06-01",
    "Principal Amount": 1000,
    "Interest Amount": 35,
    "Install Amount": 1035,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1035,
    Sign: "-",
  },
  {
    "Ins No.": 6,
    Date: "2023-07-01",
    "Principal Amount": 1000,
    "Interest Amount": 30,
    "Install Amount": 1030,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1030,
    Sign: "-",
  },
  {
    "Ins No.": 7,
    Date: "2023-08-01",
    "Principal Amount": 1000,
    "Interest Amount": 25,
    "Install Amount": 1025,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1025,
    Sign: "-",
  },
  {
    "Ins No.": 8,
    Date: "2023-09-01",
    "Principal Amount": 1000,
    "Interest Amount": 20,
    "Install Amount": 1020,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1020,
    Sign: "-",
  },
  {
    "Ins No.": 9,
    Date: "2023-10-01",
    "Principal Amount": 1000,
    "Interest Amount": 15,
    "Install Amount": 1015,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1015,
    Sign: "-",
  },
  {
    "Ins No.": 10,
    Date: "2023-11-01",
    "Principal Amount": 1000,
    "Interest Amount": 10,
    "Install Amount": 1010,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1010,
    Sign: "-",
  },
  {
    "Ins No.": 1,
    Date: "2023-03-01",
    "Principal Amount": 1000,
    "Interest Amount": 50,
    "Install Amount": 1050,
    "Collection Date": "2023-03-15",
    "Amount Collected": 1050,
    "Outstanding Principal": 0,
    Sign: "+",
  },
  {
    "Ins No.": 2,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 3,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 4,
    Date: "2023-05-01",
    "Principal Amount": 1000,
    "Interest Amount": 40,
    "Install Amount": 1040,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1040,
    Sign: "-",
  },
  {
    "Ins No.": 5,
    Date: "2023-06-01",
    "Principal Amount": 1000,
    "Interest Amount": 35,
    "Install Amount": 1035,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1035,
    Sign: "-",
  },
  {
    "Ins No.": 6,
    Date: "2023-07-01",
    "Principal Amount": 1000,
    "Interest Amount": 30,
    "Install Amount": 1030,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1030,
    Sign: "-",
  },
  {
    "Ins No.": 7,
    Date: "2023-08-01",
    "Principal Amount": 1000,
    "Interest Amount": 25,
    "Install Amount": 1025,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1025,
    Sign: "-",
  },
  {
    "Ins No.": 8,
    Date: "2023-09-01",
    "Principal Amount": 1000,
    "Interest Amount": 20,
    "Install Amount": 1020,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1020,
    Sign: "-",
  },
  {
    "Ins No.": 9,
    Date: "2023-10-01",
    "Principal Amount": 1000,
    "Interest Amount": 15,
    "Install Amount": 1015,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1015,
    Sign: "-",
  },
  {
    "Ins No.": 10,
    Date: "2023-11-01",
    "Principal Amount": 1000,
    "Interest Amount": 10,
    "Install Amount": 1010,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1010,
    Sign: "-",
  },
  {
    "Ins No.": 1,
    Date: "2023-03-01",
    "Principal Amount": 1000,
    "Interest Amount": 50,
    "Install Amount": 1050,
    "Collection Date": "2023-03-15",
    "Amount Collected": 1050,
    "Outstanding Principal": 0,
    Sign: "+",
  },
  {
    "Ins No.": 2,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 3,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 4,
    Date: "2023-05-01",
    "Principal Amount": 1000,
    "Interest Amount": 40,
    "Install Amount": 1040,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1040,
    Sign: "-",
  },
  {
    "Ins No.": 5,
    Date: "2023-06-01",
    "Principal Amount": 1000,
    "Interest Amount": 35,
    "Install Amount": 1035,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1035,
    Sign: "-",
  },
  {
    "Ins No.": 6,
    Date: "2023-07-01",
    "Principal Amount": 1000,
    "Interest Amount": 30,
    "Install Amount": 1030,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1030,
    Sign: "-",
  },
  {
    "Ins No.": 7,
    Date: "2023-08-01",
    "Principal Amount": 1000,
    "Interest Amount": 25,
    "Install Amount": 1025,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1025,
    Sign: "-",
  },
  {
    "Ins No.": 8,
    Date: "2023-09-01",
    "Principal Amount": 1000,
    "Interest Amount": 20,
    "Install Amount": 1020,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1020,
    Sign: "-",
  },
  {
    "Ins No.": 9,
    Date: "2023-10-01",
    "Principal Amount": 1000,
    "Interest Amount": 15,
    "Install Amount": 1015,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1015,
    Sign: "-",
  },
  {
    "Ins No.": 10,
    Date: "2023-11-01",
    "Principal Amount": 1000,
    "Interest Amount": 10,
    "Install Amount": 1010,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1010,
    Sign: "-",
  },
  {
    "Ins No.": 1,
    Date: "2023-03-01",
    "Principal Amount": 1000,
    "Interest Amount": 50,
    "Install Amount": 1050,
    "Collection Date": "2023-03-15",
    "Amount Collected": 1050,
    "Outstanding Principal": 0,
    Sign: "+",
  },
  {
    "Ins No.": 2,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 3,
    Date: "2023-04-01",
    "Principal Amount": 1000,
    "Interest Amount": 45,
    "Install Amount": 1045,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1045,
    Sign: "-",
  },
  {
    "Ins No.": 4,
    Date: "2023-05-01",
    "Principal Amount": 1000,
    "Interest Amount": 40,
    "Install Amount": 1040,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1040,
    Sign: "-",
  },
  {
    "Ins No.": 5,
    Date: "2023-06-01",
    "Principal Amount": 1000,
    "Interest Amount": 35,
    "Install Amount": 1035,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1035,
    Sign: "-",
  },
  {
    "Ins No.": 6,
    Date: "2023-07-01",
    "Principal Amount": 1000,
    "Interest Amount": 30,
    "Install Amount": 1030,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1030,
    Sign: "-",
  },
  {
    "Ins No.": 7,
    Date: "2023-08-01",
    "Principal Amount": 1000,
    "Interest Amount": 25,
    "Install Amount": 1025,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1025,
    Sign: "-",
  },
  {
    "Ins No.": 8,
    Date: "2023-09-01",
    "Principal Amount": 1000,
    "Interest Amount": 20,
    "Install Amount": 1020,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1020,
    Sign: "-",
  },
  {
    "Ins No.": 9,
    Date: "2023-10-01",
    "Principal Amount": 1000,
    "Interest Amount": 15,
    "Install Amount": 1015,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1015,
    Sign: "-",
  },
  {
    "Ins No.": 10,
    Date: "2023-11-01",
    "Principal Amount": 1000,
    "Interest Amount": 10,
    "Install Amount": 1010,
    "Collection Date": "",
    "Amount Collected": 0,
    "Outstanding Principal": 1010,
    Sign: "-",
  },
];


const tableLeft = document.getElementById("left-table");
const tableRight = document.getElementById("right-table");
const theadLeft = tableLeft.createTHead();
const theadRight = tableRight.createTHead();
const tbodyRight = tableRight.createTBody();
const tbodyLeft = tableLeft.createTBody();

//  const headers = ["name", "age", "gender", "city"];
const headers = [
  "Date",
  "Principal",
  "Amount",
  "Interest Amount",
  "Install Amount",
  "Collection Date",
  "Amount Collected",
  "Outstanding Principal",
  "Sign",
];

// create table header for right and left
const headerRowLeft = theadLeft.insertRow(0);
const headerRowRight = theadRight.insertRow(0);
for (let i = 0; i < headers.length; i++) {
  const header = document.createElement("th");
  header.innerHTML = headers[i];
  headerRowLeft.appendChild(header);
}
for (let i = 0; i < headers.length; i++) {
  const header = document.createElement("th");
  header.innerHTML = headers[i];
  headerRowRight.appendChild(header);
}

data.forEach((loan, index) => {
  const row =
    index < 44 ? tbodyLeft.insertRow(index) : tbodyRight.insertRow(index - 44);

  for (const key in loan) {
    const cell = row.insertCell();
    const value = loan[key];
    cell.textContent = value;
  }
});

//create dummy 10 array objects with names: Ins No. ; Date; Principal Amount; Interest Amount; Install Amount; Collection Date; Amount Collected; Outstanding Principal; Sign

